basePath: /api/v1
externalDocs:
  description: Brick Docs
  url: https://brick.k11v.cc/docs
host: brick.k11v.cc
info:
  contact:
    name: Brick Support
    url: http://brick.k11v.cc/support
  description: Brick is a service that builds PDF files from Markdown files.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: http://brick.k11v.cc/terms
  title: Brick API
  version: "0.0"
paths: {}
schemes:
- https
swagger: "2.0"
